version:  "3.9"

services:

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      #POSTGRES_INITDB_ARGS: '-A md5'
    ports:
      - '5432:5432'


  fpvapp:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate --settings=FpvApp.settings_files.settings && python manage.py runserver 0.0.0.0:8000 --settings=FpvApp.settings_files.settings"
    ports:
      - "8000:8000"
    depends_on:
      - pgdb

