# Generated by Django 4.2.8 on 2024-01-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('add_date', models.DateTimeField(auto_now=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LessonTopics',
                'verbose_name_plural': 'LessonTopics',
            },
        ),
    ]
