# Generated by Django 4.2.8 on 2024-01-04 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100)),
            ],
            options={
                'verbose_name': 'TagsModel',
                'verbose_name_plural': 'TagsModel',
            },
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='tag_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FpvAppMain.tagsmodel'),
        ),
    ]
