# Generated by Django 4.2.8 on 2024-01-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0002_tagsmodel_lessontopics_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessontopics',
            old_name='tag_name',
            new_name='tag_name_0',
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_1',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_2',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_3',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='tag_4',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tagsmodel',
            name='tag',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
    ]
