# Generated by Django 4.2.8 on 2024-01-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0003_rename_tag_name_lessontopics_tag_name_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontopics',
            name='tag_name_0',
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='tag_1',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='tag_2',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='tag_3',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='tag_4',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='tag_5',
            field=models.CharField(blank=True, choices=[('repair', 'repair'), ('video', 'video'), ('flying', 'flying'), ('education', 'education'), ('inventing', 'inventing')], max_length=100, null=True),
        ),
    ]
