# Generated by Django 4.2.8 on 2024-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0004_remove_lessontopics_tag_name_0_lessontopics_tag_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontopics',
            name='pic_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='pic_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='pic_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='pic_4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='pic_5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='pic_6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='text_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='text_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='text_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='text_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='text_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='text_6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
