# Generated by Django 4.2.8 on 2024-01-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0005_lessontopics_pic_1_lessontopics_pic_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontopics',
            name='pic_1',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='pic_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='pic_3',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='pic_4',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='pic_5',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='pic_6',
            field=models.ImageField(blank=True, null=True, upload_to='media/img'),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/video'),
        ),
    ]
