# Generated by Django 4.2.8 on 2024-01-22 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FpvAppMain', '0010_alter_lessontopics_pic_1_alter_lessontopics_pic_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontopics',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic/'),
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Letters',
                'verbose_name_plural': 'Letters',
            },
        ),
    ]
