# Generated by Django 4.2.8 on 2024-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0011_alter_lessontopics_pic_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='status',
            field=models.CharField(choices=[('unread', 'unread'), ('read', 'read')], default='unread', max_length=255),
        ),
    ]
