# Generated by Django 4.2.8 on 2024-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0013_lessontopics_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontopics',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessontopics',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
