# Generated by Django 4.2.8 on 2024-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0014_lessontopics_dislike_lessontopics_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontopics',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lessontopics',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
