# Generated by Django 4.2.8 on 2024-05-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FpvAppMain', '0017_commentstablemain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentstablemain',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
